# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://pbalapra.github.io/
# baseurl: /sustain/
title: Prasanna Balaprakash
author: Prasanna Balaprakash
description: Personal web page
avatar: pb.png
email: pbalapra@anl.gov
github: pbalapra # username
linkedin: prasannaprakash
gscholar: ZycQHdgAAAAJ
rgate: Prasanna_Balaprakash
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
